import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    gujaratiName: 'ટામેટા',
    englishName: 'Tomatoes',
    price: 50,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Seasonal',
    badge: 'Farm Fresh',
    emoji: '🍅',
    bgColor: '#FFF0F2', // Pink blush
    benefit: 'Rich in Vitamin C & antioxidants for skin health',
  },
  {
    id: '3',
    gujaratiName: 'ફુલાવર',
    englishName: 'Cauliflower',
    price: 80,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Seasonal',
    badge: 'Direct From Farm',
    emoji: '🥦',
    bgColor: '#FFFDE8', // Light yellow
    benefit: 'Packed with immune-boosting nutrients & vitamins',
  },
  {
    id: '4',
    gujaratiName: 'દેશી કોબીજ',
    englishName: 'Desi Cabbage',
    price: 60,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Leafy',
    badge: 'Crispy & Fresh',
    emoji: '🥬',
    bgColor: '#F0FFF5', // Soft green
    benefit: 'Great source of Vitamin K and supports gut health',
  },
  {
    id: '2',
    gujaratiName: 'ભીંડા',
    englishName: 'Okra',
    price: 100,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: '100% Organic',
    emoji: '🌿',
    bgColor: '#F2FBF2', // Mint green
    benefit: 'High in fiber to promote healthy digestion',
  },
  {
    id: '9',
    gujaratiName: 'વટાણા',
    englishName: 'Green Peas',
    price: 120,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Seasonal',
    badge: 'Sweet & Green',
    emoji: '🌿',
    bgColor: '#F0FFF5',
    benefit: 'Excellent source of protein and essential vitamins',
  },
  {
    id: '10',
    gujaratiName: 'કાચા કેળા',
    englishName: 'Raw Banana',
    price: 40,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: 'Fresh Raw',
    emoji: '🌿',
    bgColor: '#FFFDE8',
    benefit: 'Rich in starch and essential minerals',
  },
  {
    id: '11',
    gujaratiName: 'દૂધી',
    englishName: 'Bottle Gourd',
    price: 50,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: 'Cooling',
    emoji: '🌿',
    bgColor: '#F2FBF2',
    benefit: 'Extremely hydrating and easy to digest',
  },
  {
    id: '12',
    gujaratiName: 'દેશી દૂધી',
    englishName: 'Desi Bottle Gourd',
    price: 60,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: 'Tender Fresh',
    emoji: '🌿',
    bgColor: '#F2FBF2',
    benefit: 'Traditional variety with enhanced flavor',
  },
  {
    id: '13',
    gujaratiName: 'તુરીયું',
    englishName: 'Ridge Gourd',
    price: 80,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: 'Surat Fresh',
    emoji: '🌿',
    bgColor: '#F0FFF5',
    benefit: 'High in dietary fiber & active nutrients',
  },
  {
    id: '6',
    gujaratiName: 'કારેલા',
    englishName: 'Bitter Gourd',
    price: 90,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: '100% Organic',
    emoji: '🌿',
    bgColor: '#F2FBF2',
    benefit: 'Helps regulate blood sugar levels & purifies blood',
  },
  {
    id: '14',
    gujaratiName: 'ટીંડોળા',
    englishName: 'Ivy Gourd',
    price: 70,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: 'Crisp & Tiny',
    emoji: '🌿',
    bgColor: '#F5FFF5',
    benefit: 'Boosts metabolism and immune system',
  },
  {
    id: '15',
    gujaratiName: 'ચોળી',
    englishName: 'Val Beans',
    price: 100,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Seasonal',
    badge: 'Tender Pods',
    emoji: '🌿',
    bgColor: '#F0FFF5',
    benefit: 'Excellent plant-based source of protein',
  },
  {
    id: '16',
    gujaratiName: 'પાપડી',
    englishName: 'Flat Beans',
    price: 90,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Seasonal',
    badge: 'Local Harvest',
    emoji: '🌿',
    bgColor: '#FFFDE8',
    benefit: 'Great source of folate and dietary fiber',
  },
  {
    id: '17',
    gujaratiName: 'તુવેર',
    englishName: 'Pigeon Peas',
    price: 140,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Seasonal',
    badge: 'Winter Special',
    emoji: '🌿',
    bgColor: '#F2FBF2',
    benefit: 'Nutrient-rich staple loaded with minerals',
  },
  {
    id: '18',
    gujaratiName: 'દેશી કાકડી',
    englishName: 'Desi Cucumber',
    price: 50,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: 'Surat Crunchy',
    emoji: '🌿',
    bgColor: '#F0FFF5',
    benefit: 'Naturally cooling and highly hydrating',
  },
  {
    id: '19',
    gujaratiName: 'ગવાર',
    englishName: 'Cluster Beans',
    price: 80,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Seasonal',
    badge: 'Brimming Fibers',
    emoji: '🌿',
    bgColor: '#F2FBF2',
    benefit: 'Supports healthy glycemic index and digestion',
  },
  {
    id: '20',
    gujaratiName: 'મેથી',
    englishName: 'Fenugreek Leaves',
    price: 40,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Leafy',
    badge: 'Freshly Cut Joint',
    emoji: '🌿',
    bgColor: '#F0FFF5',
    benefit: 'Powerful herb beneficial for blood health',
  },
  {
    id: '21',
    gujaratiName: 'ચોલિયા ની ભાજી',
    englishName: 'Green Chickpea Leaves',
    price: 60,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Leafy',
    badge: 'Rare Delight',
    emoji: '🌿',
    bgColor: '#F2FBF2',
    benefit: 'Rich in antioxidants and iron',
  },
  {
    id: '22',
    gujaratiName: 'મકાઈ',
    englishName: 'Corn',
    price: 40,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Seasonal',
    badge: 'Golden Sweet',
    emoji: '🌽',
    bgColor: '#FFFDE8',
    benefit: 'High in fiber and energy-boosting complex carbs',
  },
  {
    id: '23',
    gujaratiName: 'લીંબુ',
    englishName: 'Lemon',
    price: 120,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: 'Zesty Citrus',
    emoji: '🍋',
    bgColor: '#FFFDE8',
    benefit: 'Excellent source of Vitamin C and alkalizer',
  },
  {
    id: '24',
    gujaratiName: 'કેપ્સિકમ',
    englishName: 'Capsicum',
    price: 105,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: 'Mild & Sweet',
    emoji: '🫑',
    bgColor: '#F0FFF5',
    benefit: 'Boosts immunity and contains metabolism-enhancing qualities',
  },
  {
    id: '25',
    gujaratiName: 'કોથમીર',
    englishName: 'Coriander',
    price: 40,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Leafy',
    badge: 'Aromatic Herb',
    emoji: '🌿',
    bgColor: '#F2FBF2',
    benefit: 'Enhances flavor while detoxifying body elements',
  },
  {
    id: '26',
    gujaratiName: 'આમળા',
    englishName: 'Indian Gooseberry',
    price: 80,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: 'Ayu Vitality',
    emoji: '🌿',
    bgColor: '#F5FFF5',
    benefit: 'Powerhouse of vitamin C for hair, eyes and immunity',
  },
  {
    id: '27',
    gujaratiName: 'ફણસી',
    englishName: 'French Beans',
    price: 110,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Seasonal',
    badge: 'Fresh Snap',
    emoji: '🌿',
    bgColor: '#F2FBF2',
    benefit: 'High in antioxidant vitamins A and C',
  },
  {
    id: '28',
    gujaratiName: 'લાલ મોગરી',
    englishName: 'Red Radish Sprouts',
    price: 90,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Leafy',
    badge: 'Crispy Sprouts',
    emoji: '🌿',
    bgColor: '#FFF0F2',
    benefit: 'Peppery taste packed with vital micronutrients',
  },
  {
    id: '29',
    gujaratiName: 'લીલી મોગરી',
    englishName: 'Green Radish Sprouts',
    price: 90,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Leafy',
    badge: 'Healthy Pods',
    emoji: '🌿',
    bgColor: '#F2FBF2',
    benefit: 'Traditional Gujarati sprout loaded with fibers',
  },
  {
    id: '30',
    gujaratiName: 'રેગ્યુલર મરચા',
    englishName: 'Regular Chilli',
    price: 80,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: 'Spicy Kick',
    emoji: '🌿',
    bgColor: '#F0FFF5',
    benefit: 'Speeds up metabolism with capsaicin properties',
  },
  {
    id: '31',
    gujaratiName: 'મોરા મરચા',
    englishName: 'Mora Chilli',
    price: 70,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: 'Mild Spice',
    emoji: '🌿',
    bgColor: '#F2FBF2',
    benefit: 'Slightly sweet and ideal for stuffing or daily fry',
  },
  {
    id: '32',
    gujaratiName: 'લાલ મરચા',
    englishName: 'Red Chilli',
    price: 90,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: 'Fiery Crisp',
    emoji: '🌿',
    bgColor: '#FFF0F2',
    benefit: 'Rich in vitamins and provides natural warm spice',
  },
  {
    id: '33',
    gujaratiName: 'લવીંગ્યા મરચા',
    englishName: 'Lavinya Chilli',
    price: 100,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: 'Very Spicy',
    emoji: '🌿',
    bgColor: '#F5FFF5',
    benefit: 'Traditional heirloom hot pepper for rich curries',
  },
  {
    id: '34',
    gujaratiName: 'કાચી કેરી',
    englishName: 'Raw Mango',
    price: 80,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Fruits',
    badge: 'Tangy Treats',
    emoji: '🌿',
    bgColor: '#FFFDE8',
    benefit: 'Ideal for pickles, refreshments and sweet-sour chutneys',
  },
  {
    id: '35',
    gujaratiName: 'પરવર',
    englishName: 'Pointed Gourd',
    price: 120,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: 'Gujarati Curry Elite',
    emoji: '🌿',
    bgColor: '#F0FFF5',
    benefit: 'Aids blood purification and healthy gut',
  },
  {
    id: '36',
    gujaratiName: 'ફુદિનો',
    englishName: 'Mint Leaves',
    price: 30,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Leafy',
    badge: 'Super Cool',
    emoji: '🌿',
    bgColor: '#F2FBF2',
    benefit: 'Refreshing digestive aid with soothing aroma',
  },
  {
    id: '37',
    gujaratiName: 'મીઠો લીમડો',
    englishName: 'Sweet Neem Leaves',
    price: 30,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Leafy',
    badge: 'Curry Essential',
    emoji: '🌿',
    bgColor: '#F0FFF5',
    benefit: 'Keeps heart healthy and promotes sound digestion',
  },
  {
    id: '38',
    gujaratiName: 'બ્રોકલી',
    englishName: 'Broccoli',
    price: 250,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: 'Exotic Green',
    emoji: '🥦',
    bgColor: '#F0FFF5',
    benefit: 'High in antioxidants, fibers and supports brain health',
  },
  {
    id: '39',
    gujaratiName: 'જૂગની',
    englishName: 'Zucchini',
    price: 180,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: 'Exotic Gourd',
    emoji: '🥒',
    bgColor: '#F2FBF2',
    benefit: 'Low-calorie delight loaded with positive nutrients',
  },
  {
    id: '40',
    gujaratiName: 'બેબીકોન',
    englishName: 'Baby Corn',
    price: 120,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Seasonal',
    badge: 'Crisp Exotic',
    emoji: '🌽',
    bgColor: '#FFFDE8',
    benefit: 'Rich in dietary fiber and essential minerals',
  },
  {
    id: '41',
    gujaratiName: 'બેસિલ પત્તા',
    englishName: 'Basil Leaves',
    price: 50,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Leafy',
    badge: 'Exotic Herb',
    emoji: '🌿',
    bgColor: '#F0FFF5',
    benefit: 'Rich in therapeutic oils and health boosting properties',
  },
  {
    id: '42',
    gujaratiName: 'લાલ કેપ્સિકમ',
    englishName: 'Red Capsicum',
    price: 180,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: 'Color Palette',
    emoji: '🫑',
    bgColor: '#FFF0F2',
    benefit: 'Packed with sweet zest and huge Vitamin C volume',
  },
  {
    id: '43',
    gujaratiName: 'પીળું કેપ્સિકમ',
    englishName: 'Yellow Capsicum',
    price: 180,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Organic',
    badge: 'Sweet & Zesty',
    emoji: '🫑',
    bgColor: '#FFFDE8',
    benefit: 'Full of potassium keeping cardiovascular health perfect',
  },
  {
    id: '44',
    gujaratiName: 'લીલી ચા',
    englishName: 'Green Tea Leaves',
    price: 140,
    baseUnit: 'KG',
    availableUnits: ['KG', 'GRAM'],
    category: 'Leafy',
    badge: 'Herbal Wellness',
    emoji: '🌿',
    bgColor: '#F2FBF2',
    benefit: 'Ultimate antioxidant source boosting energy levels',
  },
  {
    id: '5',
    gujaratiName: 'હાફુસ કેરી',
    englishName: 'Alphonso Mango',
    price: 750,
    baseUnit: 'DOZEN',
    availableUnits: ['DOZEN', 'KG'],
    category: 'Fruits',
    badge: 'Sweet & Premium',
    emoji: '🥭',
    bgColor: '#FFF8F0', // Peachy cream
    benefit: 'Rich in Vitamin A, boosts energy & immunity',
  }
];

export const CATEGORIES = ['All', 'Leafy', 'Root', 'Seasonal', 'Organic', 'Fruits'];

export const HEALTH_BENEFITS = [
  {
    id: 'tomato',
    emoji: '🍅',
    name: 'Tomato',
    benefit: 'Rich in Vitamin C',
    bgColor: 'bg-red-50 hover:bg-red-100/70',
    textColor: 'text-red-600',
    badgeColor: 'bg-red-100/50 text-red-700',
  },
  {
    id: 'carrot',
    emoji: '🌿',
    name: 'Carrot',
    benefit: 'Good for eyesight',
    bgColor: 'bg-orange-50 hover:bg-orange-100/70',
    textColor: 'text-orange-600',
    badgeColor: 'bg-orange-100/50 text-orange-700',
  },
  {
    id: 'spinach',
    emoji: '🌿',
    name: 'Spinach',
    benefit: 'High in iron',
    bgColor: 'bg-emerald-50 hover:bg-emerald-100/70',
    textColor: 'text-emerald-600',
    badgeColor: 'bg-emerald-100/50 text-emerald-700',
  },
  {
    id: 'cucumber',
    emoji: '🥒',
    name: 'Cucumber',
    benefit: 'Hydrates the body',
    bgColor: 'bg-green-50 hover:bg-green-100/70',
    textColor: 'text-green-600',
    badgeColor: 'bg-green-100/50 text-green-700',
  },
  {
    id: 'beetroot',
    emoji: '🥬', // beetroot style
    name: 'Beetroot',
    benefit: 'Supports blood flow',
    bgColor: 'bg-pink-50 hover:bg-pink-100/70',
    textColor: 'text-pink-600',
    badgeColor: 'bg-pink-100/50 text-pink-700',
  },
  {
    id: 'broccoli',
    emoji: '🥦',
    name: 'Broccoli',
    benefit: 'Boosts immunity',
    bgColor: 'bg-lime-50 hover:bg-lime-100/70',
    textColor: 'text-lime-700',
    badgeColor: 'bg-lime-100/50 text-lime-800',
  },
  {
    id: 'lemon',
    emoji: '🍋',
    name: 'Lemon',
    benefit: 'Improves digestion',
    bgColor: 'bg-yellow-50 hover:bg-yellow-100/70',
    textColor: 'text-yellow-600',
    badgeColor: 'bg-yellow-100/50 text-yellow-700',
  },
  {
    id: 'capsicum',
    emoji: '🫑',
    name: 'Capsicum',
    benefit: 'Packed with antioxidants',
    bgColor: 'bg-[#EAF6EA] hover:bg-green-100/70',
    textColor: 'text-[#2E7D32]',
    badgeColor: 'bg-green-100/50 text-green-700',
  }
];
